### ISSUE TITLE
Establish a common code style

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-itoolkit#21]
I propose we should:

- use `eslint` to maintain consistent styling throughout the project.

- import and use the same `.eslintrc` used by the [idb-pconnector](https://github.com/IBM/nodejs-idb-pconnector/blob/master/.eslintrc)

@IBM/ibmi-open-source 

Also would like to add JSdoc annotations to the classes.

What do you all think?

If approved I will lint all files in the project and submit a PR.

**Comment by markdirish** [comment]
We should probably get a standard one across _all_ projects. Is the one in idb-pconnector good? There are some really famous JavaScript style guides we might follow, like the [AirBNB JavaScript style guide](https://github.com/airbnb/javascript). Might be easier to use a tried and tested one like that. 

This is a great idea though.

**Comment by abmusse** [comment]
> We should probably get a standard one across all projects
I totally agree

I enjoyed using that eslint file for `idb-pconnector` project.

I'm open to looking into other style guides,

It really comes to preference when choosing from the popular style guides,

For example:

some enforce semicolons after each line while others do not.

Of course we can use their style guide as a base and tweak it to our liking.

**Comment by kadler** [comment]
If we're going to switch things up and enforce a style, there's going to be a lot of changes, which will make history harder to follow (`git blame`, etc). Usually when this is done, you do it in one big change that's a clear divider line between old and new, so this should be top priority.

I'd also echo @markdirish's suggestion to use a common community style. I would not customize it, but stick to the style since that would mean less friction for outside developers to contribute.

**Comment by markdirish** [comment]
It seems my initial sense that the airbnb style as a sort of 'gold standard' seems to be correct. I followed the instructions [on this website](https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6) to install eslint and airbnb style as devDependencies (which we should eventually do for all our repos). I am currently running the linter instructions from eslints website under **Local Installation and Usage**: [Eslint Getting Started](https://eslint.org/docs/user-guide/getting-started).

There are a few configurations in the style that are weird to me (100 max line length instead of 80), but I think I agree with @kadler that we shouldn't change it, and should instead adapt the way we code. That will help keep the code standardized.

I am going to lint this repo and push to a new v1.0 branch, since that is the milestone we are shooting for. We can then work on some of the other improvements/enhancements on that branch and get this repo ready for 1.0

**Comment by markdirish** [comment]
One issue that I've run into is the ['new-cap' rule](https://eslint.org/docs/rules/new-cap#require-constructor-names-to-begin-with-a-capital-letter-new-cap), which says that constructors (and by extension classes) need to begin with a capital letter. Obviously this becomes an issue for our tendency to preface our class names with **i**, as in **iPgm**. If we are going to adopt this, we are going to have to change to IPgm, which I don't have a problem with, but I want to feel out how everyone feels.

**Comment by kadler** [comment]
@markdirish Yes, we can't break compatibility, but we can disable linting for those lines: https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments

Ideally, we'd also come up with an API which is conformant and make the old APIs deprecated, but that should be a separate issue.

**Comment by abmusse** [comment]
Also noticed that guide this [disallows `for of`](https://github.com/airbnb/javascript/issues/1271) which I do not totally agree with.

Some use cases where I would want `for of` when iterating over a list then using `await` on a method that returns a promise. 

The guide recommends using `for each` method which does not play nice with async and await.
[see this](https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404)

I could using the good old `for(let i = 0; i < list.length; i++)` but the `for of` statement is much cleaner imo.

**Comment by abmusse** [comment]
Closing this since we established common code style with [AirBNB JavaScript style guide](https://github.com/airbnb/javascript).
