### ISSUE TITLE
Removal of sync functions

### ISSUE THREAD

**Issue by markdirish** [IBM/nodejs-itoolkit#32]
In the currently published package, there is the option to do synchronous calls to the various functions in the iDataQueue, iNetwork, iObj, iProd, iUserSpace, and iWork. 

As currently implemented, calling synchronously is a mess. It looks like the code creates a timeout to check if the result has been returned. If not, it creates ANOTHER timeout to check if the result is returned, spinning more and more timeouts until it either returns or _timesout_. Just doing static analysis of the code, I'm not even convinced it returns correctly, and I believe there has been customer confusion in the past when trying to use this package synchronously.

Because no one should be using this package synchronously anyway, @abmusse  and I believe that we should remove all that logic and, for now, assume that the user is passing a callback function. Once we get that baked in, we can look at using more modern asynchronous methods like Promises.

**Comment by kadler** [comment]
FYI, @abmusse and I ran through the code sequence and since calling the transport with the sync option set to true causes it to be synchronous, it will not return until it has a value and called the callback, which means that the whole timeout and retry logic is pointless. Indeed, if it was not the case that stop was set to 1 before waitForTimeout was run, there would be no way to retrieve the result (as waitForResult would return the result to setTimeout instead of the actual caller.

**Comment by markdirish** [comment]
Yeah, it was a mess. Even if we decide to keep sync methods, the way it was written before needed to be excised either way. Good info.

**Comment by kadler** [comment]
I doubt anyone cares about sync, and if they do they could wrap it in a promise or something.

**Comment by abmusse** [comment]
Resolved by 7fdf0fd
