### ISSUE TITLE
Deprecated dependencies in npm itoolkit package

### ISSUE THREAD

**Issue by MHirian** [IBM/nodejs-itoolkit#402]
* **Node.js version**:
* **itoolkit version**:
* **IBM i version**:
* **XMLSERVICE version**:

**Describe the bug**
This is a bug per se. This is more of deprecated packages showing up in the dependencies

**To Reproduce**
1. Download itoolkit into a new project to view the deprecated packages OR

**Expected behavior**
Newer version which does not show the deprecated dependency packages upon itoolkit download

**Screenshots**
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@3.0.2: This package is no longer supported.

**Comment by kadler** [comment]
None of these are used directly by itoolkit, but are dependencies of some of our dependencies.

Looks like mocha pulls in glob which pulls in inflight, node-pre-gyp pulls in rimraf along with npmlog which pulls in are-we-there-yet and gauge.

So updating mocha and node-pre-gyp should be done, though for node-pre-gyp, I don't know if that will resolve it since they haven't put out a new release in over a year.

Either way, node-pre-gyp is only used during installation of the package (so the memory leak isn't that problematic) and mocha is only used for testing and is listed as a dev dependency.

**Comment by MHirian** [comment]
Sounds good @kadler. I have updated the packages. Thanks for the support. We can close this issue?
